trigger: none
pr: none

parameters:
- name: environment
  displayName: Select Environment
  type: string
  default: dev
  values:
    - dev
    - test
    - prod
    - other

pool:
  vmImage: ubuntu-latest

steps:

- bash: |
    echo "Environment = ${{ parameters.environment }}"
