trigger:
- main

pr: none

pool:
  vmImage: ubuntu-latest

jobs:

- job: Job1

  steps:

  - script: |
      echo "Hello Azure" > demo.txt
      ls -la
      cat demo.txt

- job: Job2

  dependsOn: Job1

  steps:

  - script: |  
      echo "Trying to read..."
      ls -la
      cat demo.txt



      
