trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

stages:

- stage: Validate
  jobs:
  - job: ValidateJob
    steps:
    - bash: |
        echo "Terraform Validate"

- stage: Plan
  dependsOn: Validate
  jobs:
  - job: PlanJob
    steps:
    - bash: |
        echo "Terraform Plan"

- stage: Apply
  dependsOn: Plan
  jobs:
  - job: ApplyJob
    steps:
    - bash: |
        echo "Terraform Apply"
        exit 1
